name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-go:
    name: Build Go App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.1'

      - name: Build Go app
        run: go build -o dist/sugar-go sugar.go

      - name: Bundle Go app
        uses: actions/upload-artifact@v4
        with:
          name: sugar-go
          path: dist/sugar-go

  build-python:
    name: Build Python App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PyInstaller
        run: pyinstaller --onefile --name=sugar-py sugar.py

      - name: Bundle Python app
        uses: actions/upload-artifact@v4
        with:
          name: sugar-py
          path: dist/sugar-py
