name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-go:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Create dotenv file'
        run: |
          touch .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.1'

      - name: Build app
        run: go build -o dist/sugar sugar.go

      - name: Bundle app
        uses: actions/upload-artifact@v4
        with:
          name: sugar
          path: dist/sugar
